#! /usr/bin/python
'''
 *  $Id: JobOpt_DmpCalBgoPed, 2014-10-11 DAMPE $
 *  Author(s): USTC

      Pedestal Calibration:
      Append: CorAlgBgoDac,
              CalAlgBgoPed;
              
'''

#-------------------------------------------------------------------
import sys
import DMPSW                    # Load DAMPE software
import libDmpAlgBgoDacor as DmpBgoDacor
import libDmpBgoPed as DmpBgoPed

#-------------------------------------------------------------------
#input file name
seg=len(sys.argv[1])
if seg == 0:
  print 'Usage: ./job inputpath/inputfile'

suffix = 0

for i in range(0,len(sys.argv[1]),1):
	if sys.argv[1][i]=='/':
	   seg=i
	if sys.argv[1][i]=='.':
	   suffix=i
	   
inputpath=sys.argv[1][0:seg]
inputfilename=sys.argv[1][(seg+1):]
inputstem=sys.argv[1][(seg+1):suffix]
#print inputstem
#-------------------------------------------------------------------
# Global setting
#DMPSW.Core.Set("EventNumber","3055")     # If NOT set, will use 1234567890
#DMPSW.Core.Set("StartTime","20130101-0000")     # if NOT set, start from launch time
#DMPSW.Core.Set("StopTime","20160101-0000")      # if NOT set, end at 2113.01.01
#DMPSW.Core.Set("LogLevel","Warning")      # Value = {Error | Warning | Info | Debug}. If NOT set, will use Info.

#-------------------------------------------------------------------
# RootIOSvc options
DMPSW.RootIOSvc.Set("Input/Path",inputpath)
DMPSW.RootIOSvc.Set("Input/FileName",inputfilename)
DMPSW.RootIOSvc.Set("Output/Path","./Pedestal/")
DMPSW.RootIOSvc.Set("Output/FileName",inputstem+"_BgoPed.root")
DMPSW.RootIOSvc.Set("Output/WriteList","Calibration/Bgo")  # split by ;

#-------------------------------------------------------------------

corBgoDac = DmpBgoDacor.DmpAlgBgoDacor()
DMPSW.AlgMgr.Append(corBgoDac)

calBgoPed = DmpBgoPed.DmpAlgBgoPed()
DMPSW.AlgMgr.Append(calBgoPed)

#-------------------------------------------------------------------
# Run job
DMPSW.Core.Initialize()
DMPSW.Core.Run()
DMPSW.Core.Finalize()

