#! /usr/bin/python
'''
 *  $Id: JobOpt_DmpCalBgoHits, 2014-10-11 DAMPE $
 *  Author(s): USTC 

      MIPs Calibration: 
      Input Raw ROOT;

      Append: CorBgoDac,
              CorBgoCutped,
	      CalBgoHits;
'''

#-------------------------------------------------------------------
import sys
import DMPSW                    # Load DAMPE software
import libDmpAlgBgoDacor as DmpBgoDacor
import libDmpAlgBgoCutped as DmpBgoCutped
import libDmpAlgBgoHits as DmpBgoHits

#-------------------------------------------------------------------
#input file name
seg=len(sys.argv[1])
if seg == 0:
  print 'Usage: ./job inputpath/inputfile'

suffix = 0

for i in range(0,len(sys.argv[1]),1):
	if sys.argv[1][i]=='/':
	   seg=i
	if sys.argv[1][i]=='.':
	   suffix=i
	   
inputpath=sys.argv[1][0:seg]
inputfilename=sys.argv[1][(seg+1):]
inputstem=sys.argv[1][(seg+1):suffix]
#print inputstem
#-------------------------------------------------------------------
# Global setting
#DMPSW.Core.Set("EventNumber","1")     # If NOT set, will use 1234567890
#DMPSW.Core.Set("StartTime","20130101-0000")     # if NOT set, start from launch time
#DMPSW.Core.Set("StopTime","20160101-0000")      # if NOT set, end at 2113.01.01
#DMPSW.Core.Set("LogLevel","Warning")      # Value = {Error | Warning | Info | Debug}. If NOT set, will use Info.

#-------------------------------------------------------------------
# RootIOSvc options
DMPSW.RootIOSvc.Set("Input/Path",inputpath)
DMPSW.RootIOSvc.Set("Input/FileName",inputfilename)
DMPSW.RootIOSvc.Set("Output/Path","./Hits/")
DMPSW.RootIOSvc.Set("Output/FileName",inputstem+"_BgoHits.root")
DMPSW.RootIOSvc.Set("Output/WriteList","Event/Cal;Event/Rdc")  # split by ;

#-------------------------------------------------------------------
# Creat user's service or algorithm
corBgoDacor = DmpBgoDacor.DmpAlgBgoDacor()
DMPSW.AlgMgr.Append(corBgoDacor)

corBgoCutped = DmpBgoCutped.DmpAlgBgoCutped()
DMPSW.AlgMgr.Append(corBgoCutped)

calBgoHits = DmpBgoHits.DmpAlgBgoHits()
DMPSW.AlgMgr.Append(calBgoHits)

#-------------------------------------------------------------------
# Run job
DMPSW.Core.Initialize()
DMPSW.Core.Run()
DMPSW.Core.Finalize()

